services:

  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo-js:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=bachorz
      - MONGO_INITDB_ROOT_PASSWORD=bachorz
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=bachorz
      - ME_CONFIG_MONGODB_ADMINPASSWORD=bachorz
      - ME_CONFIG_MONGODB_SERVER=mongo_db

volumes:
  mongodb: {}
