spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: bachorzdb
      username: bachorz
      password: bachorz
      authentication-database: admin
#      uri: mongodb://bachorz:bachorz@localhost:27017/bachorzdb?authSource=admin&replicaSet=myRepl

